/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package artgallery.Admin;

import artgallery.DAO.ConnectionProvider;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.table.TableModel;

/**
 *
 * @author nhmng
 */
public class ArtworksManageAdmin extends javax.swing.JFrame {
    private int selectedID = 0;

    /**
     * Creates new form ManageAccount
     */
    public ArtworksManageAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        aboutTXT.setLineWrap(true);
        aboutTXT.setWrapStyleWord(true);

    }
    
    private boolean validateFields(String formType){
        if(formType.equals("edit") && !idTXT.getText().equals("") && !titleTXT.getText().equals("") && !aboutTXT.getText().equals("") && !createdyearTXT.getText().equals("") && !galleryidTXT.getText().equals("") && !artistidTXT.getText().equals("")){
            return false;
        }
        else if (formType.equals("new") && (!titleTXT.getText().equals("") && !aboutTXT.getText().equals("") && !createdyearTXT.getText().equals("") && !galleryidTXT.getText().equals("") && !artistidTXT.getText().equals(""))){
            return false;
        }
        else{
            return true;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        artworkTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        idTXT = new javax.swing.JTextField();
        titleTXT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        createdyearTXT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        forsaleCB = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        aboutTXT = new javax.swing.JTextArea();
        priceTXT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        galleryidTXT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        artistidTXT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setText("Artworks Manage");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 33, 344, 40));

        artworkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "About", "Created year", "For sale?", "Price", "Gallery ID", "Artist ID"
            }
        ));
        artworkTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                artworkTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(artworkTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 85, -1, 500));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 12, 340, 24));

        idTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTXTActionPerformed(evt);
            }
        });
        getContentPane().add(idTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 42, 300, 30));
        getContentPane().add(titleTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 310, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Title");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 340, 24));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("About");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 340, 24));

        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 79, -1));

        resetButton.setText("RESET");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 73, -1));

        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 79, -1));

        closeButton.setText("CLOSE");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 73, -1));

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 90, -1));
        getContentPane().add(createdyearTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 300, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Created year");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 340, 24));

        forsaleCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True", "False" }));
        getContentPane().add(forsaleCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 120, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("For sale");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Price");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, -1, 20));

        aboutTXT.setColumns(20);
        aboutTXT.setRows(5);
        jScrollPane2.setViewportView(aboutTXT);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 310, 80));
        getContentPane().add(priceTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 120, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Gallery ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, 20));
        getContentPane().add(galleryidTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 120, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Artist ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, -1, 20));
        getContentPane().add(artistidTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) artworkTable.getModel();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM artworks");
            while (rs.next()){
                model.addRow(new Object[]{rs.getString("ID"), rs.getString("title"), rs.getString("about"), rs.getString("created_year"), rs.getString("is_for_sale"), rs.getString("price"), rs.getString("gallery_id"), rs.getString("artist_id") });
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);    
        }
        
        deleteButton.setEnabled(false);
        updateButton.setEnabled(false);
        idTXT.setEnabled(false);
    }//GEN-LAST:event_formComponentShown

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_closeButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String title = titleTXT.getText();
        String about = aboutTXT.getText();
        int createdyear = Integer.parseInt(createdyearTXT.getText());
        String isforsale = (String) forsaleCB.getSelectedItem();
        boolean check;
        if("True".equals(isforsale)){
            check = true;
        }
        else {
            check = false;
        }
        double price = Double.parseDouble(priceTXT.getText());
        int galleryid = Integer.parseInt(galleryidTXT.getText());
        int artistid = Integer.parseInt(artistidTXT.getText());
        
        if (validateFields("new")){
            JOptionPane.showMessageDialog(null,"All fields are required");
        }
        else {
            try{
                Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("INSERT INTO artworks(title, about, created_year,is_for_sale,price, gallery_id, artist_id) VALUES (?,?,?,?,?,?,?)");
                ps.setString(1,title);
                ps.setString(2, about);
                ps.setInt(3, createdyear);
                ps.setBoolean(4,check);
                ps.setDouble(5, price);
                ps.setInt(6, galleryid);
                ps.setInt(7, artistid);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Added Sucessfully");
                setVisible(false);
                dispose(); 
                new ArtworksManageAdmin().setVisible(true);
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void artworkTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_artworkTableMouseClicked
        int index = artworkTable.getSelectedRow();
        TableModel model = artworkTable.getModel();
        
        String id = model.getValueAt(index,0).toString();
        selectedID = Integer.parseInt(id);
        idTXT.setText(id);
        
        String title = model.getValueAt(index,1).toString();
        titleTXT.setText(title);
        
        String about = model.getValueAt(index,2).toString();
        aboutTXT.setText(about);
        
        String createdyear = model.getValueAt(index, 3).toString();
        createdyearTXT.setText(createdyear);
        
        String forsale = model.getValueAt(index,4).toString();
        if("0".equals(forsale)){
           forsaleCB.removeAllItems();
           forsaleCB.addItem("False");        
           forsaleCB.addItem("True");

        }
        else {
           forsaleCB.removeAllItems();
           forsaleCB.addItem("True");
           forsaleCB.addItem("False");
        }
        
        String price ="0";
        price = model.getValueAt(index,5).toString();
        priceTXT.setText(price);
        
        String galleryid = model.getValueAt(index,6).toString();
        galleryidTXT.setText(galleryid);

        String artistid = model.getValueAt(index,7).toString();
        artistidTXT.setText(artistid);     
        
        saveButton.setEnabled(false);
        updateButton.setEnabled(true);  
        deleteButton.setEnabled(true);
    }//GEN-LAST:event_artworkTableMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed

        String title = titleTXT.getText();
        String about = aboutTXT.getText();
        int createdyear = Integer.parseInt(createdyearTXT.getText());
        String isforsale = (String) forsaleCB.getSelectedItem();
        boolean check;
        if("True".equals(isforsale)){
            check = true;
        }
        else {
            check = false;
        }
        double price = Double.parseDouble(priceTXT.getText());
        int galleryid = Integer.parseInt(galleryidTXT.getText());
        int artistid = Integer.parseInt(artistidTXT.getText());
        
        if (validateFields("edit")){
            JOptionPane.showMessageDialog(null,"All fields are required");
        }
        else {
            try{
                Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("UPDATE artworks SET title=?, about=?, created_year = ?, is_for_sale = ?, price = ?, gallery_id = ?, artist_id = ? WHERE id = ?");
                ps.setString(1,title);
                ps.setString(2, about);
                ps.setInt(3, createdyear);
                ps.setBoolean(4,check);
                ps.setDouble(5, price);
                ps.setInt(6, galleryid);
                ps.setInt(7, artistid);
                ps.setInt(8,selectedID);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Updated Sucessfully");
                setVisible(false);
                dispose(); 
                new ArtworksManageAdmin().setVisible(true);
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object
        new ArtworksManageAdmin().setVisible(true);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int a = JOptionPane.showConfirmDialog(null,"Do you want to delete this row?","Select",JOptionPane.YES_NO_OPTION);
        if ( a==0){
            try{
                Connection con = ConnectionProvider.getCon();
                Statement st = con.createStatement();
                PreparedStatement ps = con.prepareStatement("DELETE FROM artworks WHERE id=?");
                ps.setInt(1,selectedID);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Deleted Sucessfully");

                setVisible(false); //you can't see me!
                dispose(); //Destroy the JFrame object
                new ArtworksManageAdmin().setVisible(true);            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null,e);
            }  
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void idTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTXTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArtworksManageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArtworksManageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArtworksManageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArtworksManageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArtworksManageAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aboutTXT;
    private javax.swing.JTextField artistidTXT;
    private javax.swing.JTable artworkTable;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField createdyearTXT;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox<String> forsaleCB;
    private javax.swing.JTextField galleryidTXT;
    private javax.swing.JTextField idTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField priceTXT;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField titleTXT;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
