/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package art.Admin;

import art.Admin.SignupShipper;
import art.Admin.ShippersManageAdmin;
import art.Admin.ArtworksManageAdmin;
import art.Admin.SignupUsers;
import art.Admin.AccountsManageAdmin;
import art.Admin.OrdersManageAdmin;
import art.Admin.SignupGalleries;
import art.Admin.RolesManageAdmin;
import art.Admin.ItemsManageAdmin;
import art.Admin.UsersManageAdmin;
import art.Admin.ExhibitionsManageAdmin;
import art.Admin.GalleriesManageAdmin;
import art.Login;
import javax.swing.JOptionPane;

public class HomeAdmin extends javax.swing.JFrame {
    private int user_ID = 0;
    

    /**
     * Creates new form home
     */
    public HomeAdmin() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public HomeAdmin(int user_id) {
        initComponents();
        setLocationRelativeTo(null);
        user_ID = user_id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        galleriesButton = new javax.swing.JButton();
        usersButton = new javax.swing.JButton();
        shippersButton = new javax.swing.JButton();
        ordersButton = new javax.swing.JButton();
        exhibitionsButton = new javax.swing.JButton();
        artworksButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        itemButton = new javax.swing.JButton();
        roleBUTTON = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        accountBUTTON = new javax.swing.JButton();
        createuserBUTTON = new javax.swing.JButton();
        creategalleryBUTTON = new javax.swing.JButton();
        createdshipperBUTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        galleriesButton.setText("Galleries");
        galleriesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                galleriesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(galleriesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 203, 154, -1));

        usersButton.setText("Users");
        usersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersButtonActionPerformed(evt);
            }
        });
        getContentPane().add(usersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 154, -1));

        shippersButton.setText("Shippers");
        shippersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shippersButtonActionPerformed(evt);
            }
        });
        getContentPane().add(shippersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 246, 154, -1));

        ordersButton.setText("Orders");
        ordersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ordersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 375, 154, -1));

        exhibitionsButton.setText("Exhibitions");
        exhibitionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exhibitionsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exhibitionsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 332, 154, -1));

        artworksButton.setText("Artworks");
        artworksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artworksButtonActionPerformed(evt);
            }
        });
        getContentPane().add(artworksButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 289, 154, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("WELCOME ADMIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 37, 344, -1));

        logoutButton.setText("LOGOUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 35, 99, -1));

        itemButton.setText("Items");
        itemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemButtonActionPerformed(evt);
            }
        });
        getContentPane().add(itemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 412, 154, -1));

        roleBUTTON.setText("Roles");
        roleBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleBUTTONActionPerformed(evt);
            }
        });
        getContentPane().add(roleBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 455, 154, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Database Manage:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 89, 154, -1));

        jLabel3.setText("Function:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 152, -1));

        accountBUTTON.setText("Accounts");
        accountBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountBUTTONActionPerformed(evt);
            }
        });
        getContentPane().add(accountBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 117, 154, -1));

        createuserBUTTON.setText("Sign up USER account");
        createuserBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createuserBUTTONActionPerformed(evt);
            }
        });
        getContentPane().add(createuserBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 220, -1));

        creategalleryBUTTON.setText("Sign up GALLERY account");
        creategalleryBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creategalleryBUTTONActionPerformed(evt);
            }
        });
        getContentPane().add(creategalleryBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 220, -1));

        createdshipperBUTTON.setText("Sign up SHIPPER account");
        createdshipperBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createdshipperBUTTONActionPerformed(evt);
            }
        });
        getContentPane().add(createdshipperBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void galleriesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_galleriesButtonActionPerformed
        new GalleriesManageAdmin().setVisible(true); 
    }//GEN-LAST:event_galleriesButtonActionPerformed

    private void shippersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shippersButtonActionPerformed
        new ShippersManageAdmin().setVisible(true); 
    }//GEN-LAST:event_shippersButtonActionPerformed

    private void ordersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersButtonActionPerformed
        new OrdersManageAdmin().setVisible(true); 
    }//GEN-LAST:event_ordersButtonActionPerformed

    private void exhibitionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exhibitionsButtonActionPerformed
        new ExhibitionsManageAdmin().setVisible(true); 
    }//GEN-LAST:event_exhibitionsButtonActionPerformed

    private void artworksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artworksButtonActionPerformed
        new ArtworksManageAdmin().setVisible(true); 
    }//GEN-LAST:event_artworksButtonActionPerformed

    private void usersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersButtonActionPerformed
        new UsersManageAdmin().setVisible(true); 
    }//GEN-LAST:event_usersButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int a = JOptionPane.showConfirmDialog(null,"Do you want to logout application?","Select",JOptionPane.YES_NO_OPTION);
        if (a==0){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void itemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemButtonActionPerformed
        new ItemsManageAdmin().setVisible(true);
    }//GEN-LAST:event_itemButtonActionPerformed

    private void roleBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleBUTTONActionPerformed
        new RolesManageAdmin().setVisible(true); 
    }//GEN-LAST:event_roleBUTTONActionPerformed

    private void accountBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountBUTTONActionPerformed
        new AccountsManageAdmin().setVisible(true); 
    }//GEN-LAST:event_accountBUTTONActionPerformed

    private void createuserBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createuserBUTTONActionPerformed
        new SignupUsers().setVisible(true);
    }//GEN-LAST:event_createuserBUTTONActionPerformed

    private void creategalleryBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creategalleryBUTTONActionPerformed
        new SignupGalleries().setVisible(true);
    }//GEN-LAST:event_creategalleryBUTTONActionPerformed

    private void createdshipperBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createdshipperBUTTONActionPerformed
        new SignupShipper().setVisible(true);
    }//GEN-LAST:event_createdshipperBUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountBUTTON;
    private javax.swing.JButton artworksButton;
    private javax.swing.JButton createdshipperBUTTON;
    private javax.swing.JButton creategalleryBUTTON;
    private javax.swing.JButton createuserBUTTON;
    private javax.swing.JButton exhibitionsButton;
    private javax.swing.JButton galleriesButton;
    private javax.swing.JButton itemButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton ordersButton;
    private javax.swing.JButton roleBUTTON;
    private javax.swing.JButton shippersButton;
    private javax.swing.JButton usersButton;
    // End of variables declaration//GEN-END:variables
}
