/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package art.Admin;

import art.DAO.ConnectionProvider;
import javax.swing.JOptionPane;
import java.sql.*;


public class SignupGalleries extends javax.swing.JFrame {

    /**
     * Creates new form SignupAdmin
     */
    public SignupGalleries() {
        initComponents();
        setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        closeBUTTON = new javax.swing.JButton();
        signupBUTTON = new javax.swing.JButton();
        usernameTXT = new javax.swing.JTextField();
        nameTXT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addressTXT = new javax.swing.JTextField();
        passwordTXT = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("SIGN UP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 35, 170, 60));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 140, 27));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 167, 140, 21));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Galleries name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 140, 21));

        closeBUTTON.setText("BACK");
        closeBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBUTTONActionPerformed(evt);
            }
        });
        getContentPane().add(closeBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        signupBUTTON.setText("SIGN UP");
        signupBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBUTTONActionPerformed(evt);
            }
        });
        getContentPane().add(signupBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 461, 100, 33));
        getContentPane().add(usernameTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 610, 25));
        getContentPane().add(nameTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 615, 25));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 323, 400, 21));
        getContentPane().add(addressTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 615, 25));

        passwordTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTXTActionPerformed(evt);
            }
        });
        getContentPane().add(passwordTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 610, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTXTActionPerformed

    private void signupBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBUTTONActionPerformed
        String username = usernameTXT.getText();
        String password = String.valueOf(passwordTXT.getPassword());
        String name = nameTXT.getText();
        String address = addressTXT.getText();

        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            PreparedStatement ps1 = con.prepareStatement("INSERT INTO accounts(username,password,role_id) VALUES (?,?,3)");
            ps1.setString(1, username);
            ps1.setString(2, password);
            ps1.executeUpdate();
            
            
            ResultSet rs = st.executeQuery("SELECT id FROM `accounts` where username = '"+username+"' and password = '"+password+"'");
            rs.next();
            int accountID = rs.getInt("id");
            
            PreparedStatement ps = con.prepareStatement("INSERT INTO galleries(gallery_name, address, account_id) VALUES (?,?,?)");
            ps.setString(1,name);
            ps.setString(2,address);
            ps.setInt(3,accountID);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Create account sucessfully");
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }


    }//GEN-LAST:event_signupBUTTONActionPerformed

    private void closeBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBUTTONActionPerformed
        // TODO add your handling code here:
        setVisible(false); //u can't see me!
        dispose(); //Destroy the JFme     }//GEN-LAST:event_closeBUTTONActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupGalleries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupGalleries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupGalleries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupGalleries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupGalleries().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTXT;
    private javax.swing.JButton closeBUTTON;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameTXT;
    private javax.swing.JPasswordField passwordTXT;
    private javax.swing.JButton signupBUTTON;
    private javax.swing.JTextField usernameTXT;
    // End of variables declaration//GEN-END:variables
}
