/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package artgallery;

import artgallery.User.ArtworksUser;
import artgallery.User.OrdersManageUser;
import artgallery.DAO.ConnectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


public class HomeUser extends javax.swing.JFrame {
    private int userID = 0;
    private int accountID = 0;

    /**
     * Creates new form home
     */
    public HomeUser() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public HomeUser(int user_id) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.accountID = user_id;
        
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT username FROM `accounts` where id = '"+accountID+"'");
            rs.next();
            String username = rs.getString("username");
            jLabel1.setText("Welcome "+username);
            rs = st.executeQuery("SELECT * FROM `users` where account_id = '"+accountID+"'");
            rs.next();
            userID = rs.getInt("id");
        }
        
        
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        artworkBUTTON = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        oderBUTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        artworkBUTTON.setText("BROWSE ARTWORKS");
        artworkBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artworkBUTTONActionPerformed(evt);
            }
        });
        getContentPane().add(artworkBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 750, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("WELCOME USER:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 37, 344, -1));

        logoutButton.setText("LOGOUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 35, 99, -1));

        jLabel3.setText("Function:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 152, -1));

        oderBUTTON.setText("BROWSE ORDERS");
        oderBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oderBUTTONActionPerformed(evt);
            }
        });
        getContentPane().add(oderBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 750, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void artworkBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artworkBUTTONActionPerformed
        new ArtworksUser(userID).setVisible(true);
    }//GEN-LAST:event_artworkBUTTONActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int a = JOptionPane.showConfirmDialog(null,"Do you want to logout application?","Select",JOptionPane.YES_NO_OPTION);
        if (a==0){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void oderBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oderBUTTONActionPerformed
        new OrdersManageUser(userID).setVisible(true);
    }//GEN-LAST:event_oderBUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton artworkBUTTON;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton oderBUTTON;
    // End of variables declaration//GEN-END:variables
}
