/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package art.User;

import art.DAO.ConnectionProvider;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.table.TableModel;

/**
 *
 * @author nhmng
 */
public class ArtworksUser extends javax.swing.JFrame {
    private int selectedID = 0;
    private int userID = 0;
    private int selectedAristID = 0;
    private int selectedExhibitionID = 0;
    /**
     * Creates new form ManageAccount
     */
    public ArtworksUser() {
        initComponents();
        setLocationRelativeTo(null);
        aboutTXT.setLineWrap(true);
        aboutTXT.setWrapStyleWord(true);
    }
    
    public ArtworksUser(int id) {
        initComponents();
        setLocationRelativeTo(null);
        aboutTXT.setLineWrap(true);
        aboutTXT.setWrapStyleWord(true);
        setAlwaysOnTop( true );
        this.userID = id;
        System.out.println(userID);
    }
    
    public ArtworksUser(int id, int artistID, int selectedExhibitionID) {
        initComponents();
        setLocationRelativeTo(null);
        aboutTXT.setLineWrap(true);
        aboutTXT.setWrapStyleWord(true);
        setAlwaysOnTop( true );
        this.userID = id;
        this.selectedAristID = artistID;
        this.selectedExhibitionID = selectedExhibitionID;
        System.out.println(selectedExhibitionID);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        artworkTable = new javax.swing.JTable();
        titleTXT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        likeBUTTON = new javax.swing.JButton();
        buyBUTTON = new javax.swing.JButton();
        backBUTTON = new javax.swing.JButton();
        createdyearTXT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        forsaleCB = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        aboutTXT = new javax.swing.JTextArea();
        priceTXT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        gallerynameTXT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        artistnameTXT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setText("Artworks Manage");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 33, 344, 40));

        artworkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "About", "Created year", "For sale?", "Price", "Gallery ID", "Artist ID"
            }
        ));
        artworkTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                artworkTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(artworkTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 85, -1, 500));
        getContentPane().add(titleTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 310, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Title");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 340, 24));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("About");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 340, 24));

        likeBUTTON.setText("LIKE");
        likeBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likeBUTTONActionPerformed(evt);
            }
        });
        getContentPane().add(likeBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 73, -1));

        buyBUTTON.setText("BUY");
        buyBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyBUTTONActionPerformed(evt);
            }
        });
        getContentPane().add(buyBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 79, -1));

        backBUTTON.setText("BACK");
        backBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBUTTONActionPerformed(evt);
            }
        });
        getContentPane().add(backBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 73, -1));
        getContentPane().add(createdyearTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 300, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Created year");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 340, 24));

        forsaleCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True", "False" }));
        getContentPane().add(forsaleCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 120, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("For sale");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Price");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, -1, 20));

        aboutTXT.setColumns(20);
        aboutTXT.setRows(5);
        jScrollPane2.setViewportView(aboutTXT);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 310, 80));
        getContentPane().add(priceTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 120, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Gallery name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, 20));
        getContentPane().add(gallerynameTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 120, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Artist name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, -1, 20));
        getContentPane().add(artistnameTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) artworkTable.getModel();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM artworks  ");
            if (selectedAristID != 0){
                rs = st.executeQuery("SELECT * FROM artworks WHERE artist_id ='"+selectedAristID+"';");
            }
            else if (selectedExhibitionID != 0 ){
            rs = st.executeQuery("SELECT * FROM ( items INNER JOIN artworks on artworks.id =items.artwork_id) WHERE items.exhibition_id ='"+selectedExhibitionID+"';");
            }
            
            while (rs.next()){
                model.addRow(new Object[]{rs.getString("ID"), rs.getString("title"), rs.getString("about"), rs.getString("created_year"), rs.getString("is_for_sale"), rs.getString("price"), rs.getString("gallery_id"), rs.getString("artist_id") });
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);    
        }
        
        artworkTable.getColumnModel().getColumn(0).setMinWidth(0);
        artworkTable.getColumnModel().getColumn(0).setMaxWidth(0);
    }//GEN-LAST:event_formComponentShown

    private void artworkTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_artworkTableMouseClicked
        int index = artworkTable.getSelectedRow();
        TableModel model = artworkTable.getModel();
        
        String id = model.getValueAt(index,0).toString();
        selectedID = Integer.parseInt(id);
        
        String title = model.getValueAt(index,1).toString();
        titleTXT.setText(title);
        
        String about = model.getValueAt(index,2).toString();
        aboutTXT.setText(about);
        
        String createdyear = model.getValueAt(index, 3).toString();
        createdyearTXT.setText(createdyear);
        
        String forsale = model.getValueAt(index,4).toString();
        if("0".equals(forsale)){
           forsaleCB.removeAllItems();
           forsaleCB.addItem("False");        
           forsaleCB.addItem("True");

        }
        else {
           forsaleCB.removeAllItems();
           forsaleCB.addItem("True");
           forsaleCB.addItem("False");
        }
        
        String price ="0";
        price = model.getValueAt(index,5).toString();
        priceTXT.setText(price);
        
        String galleryid = model.getValueAt(index,6).toString();
        String artistid = model.getValueAt(index,7).toString();

        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT gallery_name FROM `galleries` where id = '"+galleryid+"'");
            rs.next();
            String galleryName = rs.getString("gallery_name");
            gallerynameTXT.setText(galleryName);
            
            rs = st.executeQuery("SELECT fullname FROM `artists` where id = '"+artistid+"'");
            rs.next();
            String artistName = rs.getString("fullname");
            artistnameTXT.setText(artistName);
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        String isforsale = (String) forsaleCB.getSelectedItem();
        if (isforsale.equals("True")){
            buyBUTTON.setEnabled(true);  
        }
        else {
            buyBUTTON.setEnabled(false);  
        }
        
    }//GEN-LAST:event_artworkTableMouseClicked

    private void buyBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyBUTTONActionPerformed
        try{
            setVisible(false);
            new SelectShipperH(selectedID,userID).setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }  
    }//GEN-LAST:event_buyBUTTONActionPerformed

    private void likeBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likeBUTTONActionPerformed
        try{
            Connection con = ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement("INSERT INTO interactions (user_id, artwork_id, interaction_time) VALUE (?,?,now())");
            ps.setInt(1,userID);
            ps.setInt(2,selectedID);
            ps.executeUpdate();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }  
    }//GEN-LAST:event_likeBUTTONActionPerformed

    private void backBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBUTTONActionPerformed
        // TODO add your handling code here:
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_backBUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArtworksUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArtworksUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArtworksUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArtworksUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArtworksUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aboutTXT;
    private javax.swing.JTextField artistnameTXT;
    private javax.swing.JTable artworkTable;
    private javax.swing.JButton backBUTTON;
    private javax.swing.JButton buyBUTTON;
    private javax.swing.JTextField createdyearTXT;
    private javax.swing.JComboBox<String> forsaleCB;
    private javax.swing.JTextField gallerynameTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton likeBUTTON;
    private javax.swing.JTextField priceTXT;
    private javax.swing.JTextField titleTXT;
    // End of variables declaration//GEN-END:variables
}
